extends Node

enum Tower {ARCHER, CANNON, CROSSBOW, ICE_WIZARD, LIGHTNING, POISON_WIZARD}
enum Projectile {ARROW, CANNON, ICE, LIGHTNING, POISON}
enum Enemy {BAT, SLIME, BIG_SLIME, KING_SLIME, DEMON, GHOST, GOBLIN, SKELETON, ZOMBIE}
